project:
  type: website
  

website:
  title: "myQuartoProj"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - myPage.qmd

author: "CRhACKER7"
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    extensions:
      - mermaid

