project:
  type: website

author: CRhACKER7
  

website:
  title: "myQuartoProj"
#  favicon: /images/home/favicon.ico
#  back-to-top-navigation: true

#repo-url: https://github.com/CrHacker7/Quarto-project
#  repo-actions: [edit]
#  repo-branch: master
#  repo-link-target: '_blank'
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - myPage.qmd


  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    extensions:
      - mermaid

